Repository Sofi231098/TP2_Grupo23, pull requests merged in 2023-06, with the labels that each got.

#111 Modificacion consejo java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/model/Consejo.java
Labels: bug, edición

#112 Develop
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/model/Consejo.java
  TP2_Grupo23/src/main/resources/static/css/estilo.css
  TP2_Grupo23/src/main/resources/templates/index.html
  TP2_Grupo23/src/main/resources/templates/login.html
Labels: bug, edición

#118 Dependencias bd
  .gitignore
  TP2_Grupo23/pom.xml
Labels: creacion, edición

#119 Edicion archivo application properties
  TP2_Grupo23/src/main/resources/application.properties
Labels: creacion, edición

#120 Develop
  .gitignore
  TP2_Grupo23/pom.xml
  TP2_Grupo23/src/main/resources/application.properties
Labels: duplicate

#122 Remplazar codigo productos
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/ProductosController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaProductos.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/model/Producto.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
  TP2_Grupo23/src/main/resources/templates/producto_nuevo.html
  TP2_Grupo23/src/main/resources/templates/productos.html
Labels: creacion, edición

#125 Correccion dependencias bd
  TP2_Grupo23/pom.xml
Labels: edición

#126 Develop
  TP2_Grupo23/pom.xml
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/ProductosController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaProductos.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/model/Producto.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
  TP2_Grupo23/src/main/resources/templates/producto_nuevo.html
  TP2_Grupo23/src/main/resources/templates/productos.html
Labels: edición

#127 Repository
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/repository/IProductoRepository.java
Labels: diseño, creacion, edición

#138 Creacion y Correccion
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/ProductosController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaProductos.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/model/Producto.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
  TP2_Grupo23/src/main/resources/templates/producto_nuevo.html
  TP2_Grupo23/src/main/resources/templates/productos.html
Labels: corrección

#141 Renombre de archivos .Model a .Entity
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/ContactoController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/InicioController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/ProductosController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/ServiciosController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/entity/Consejo.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/entity/Contactos.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/entity/IndexModel.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/entity/Producto.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/entity/Servicios.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/entity/Sucursal.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaConsejo.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaIndex.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaProductos.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaServicios.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaSucursal.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/IConsejoService.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/IServicioService.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceImp.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/ServiciosServiceImp.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
Labels: edición

#142 Develop
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/ContactoController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/InicioController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/ProductosController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/ServiciosController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/entity/Consejo.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/entity/Contactos.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/entity/IndexModel.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/entity/Producto.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/entity/Servicios.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/entity/Sucursal.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaConsejo.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaIndex.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaProductos.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaServicios.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaSucursal.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/IConsejoService.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/IServicioService.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceImp.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/ServiciosServiceImp.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
Labels: bug, edición, java, corrección

#146 Capa Repository Sucursales:
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/entity/Sucursal.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaSucursal.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/repository/ISucursalRepository.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceMysqlImp.java
Labels: creacion, edición, java

#150 Sucursales_capa_repository
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/SucursalesController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceMysqlImp.java
  TP2_Grupo23/src/main/resources/templates/sucursal_nueva.html
  TP2_Grupo23/src/main/resources/templates/sucursales.html
Labels: Merge

#151 Mapeo de Productos.java
  TP2_Grupo23/bin/src/main/resources/templates/productos.html
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/controller/ProductosController.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/entity/Producto.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/listas/ListaProductos.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/repository/IProductoRepository.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
  TP2_Grupo23/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceMysqlImp.java
  TP2_Grupo23/src/main/resources/templates/producto_nuevo.html
Labels: Merge

#152 Rama base_de_datos
  TP2_Grupo23/src/main/resources/base_de_datos/Productos
  TP2_Grupo23/src/main/resources/base_de_datos/Servicio
  TP2_Grupo23/src/main/resources/base_de_datos/Sucursales
Labels: Merge
